/**
 * Manages the story context, including current chapter, global summary, and recent chapter summaries.
 * Handles loading, updating, pruning, and exporting context data.
 */
export class ContextManager {
    /**
     * Initializes a new instance of the ContextManager.
     * Sets up the default context structure.
     */
    constructor() {
        /**
         * @property {Object} context - The internal state of the story context.
         * @property {number} context.currentChapter - The number of the current chapter.
         * @property {string} context.globalSummary - A summary of the global story so far.
         * @property {Array<{number: number, summary: string}>} context.recentChapters - A buffer of summaries for the most recent 25 chapters.
         */
        this.context = {
            currentChapter: 0,
            globalSummary: "The story begins.",
            recentChapters: [] // Stores last 25 chapter summaries
        };
    }

    /**
     * Loads context from a parsed JSON object (e.g., from a file upload).
     * Validates and sanitizes the input to ensure the internal structure is correct.
     *
     * @param {Object} jsonContext - The context object to load.
     * @param {number} [jsonContext.currentChapter] - The current chapter number.
     * @param {string} [jsonContext.globalSummary] - The global story summary.
     * @param {Array} [jsonContext.recentChapters] - The list of recent chapter summaries.
     */
    loadContext(jsonContext) {
        if (!jsonContext) return;

        // Validation to ensure structure exists
        this.context = {
            currentChapter: jsonContext.currentChapter || 0,
            globalSummary: jsonContext.globalSummary || "",
            recentChapters: Array.isArray(jsonContext.recentChapters) ? jsonContext.recentChapters : []
        };
        console.log("Context loaded:", this.context);
    }

    /**
     * Retrieves the full context object.
     * Useful for saving the context to a file.
     *
     * @returns {Object} - The current context object containing chapter info and summaries.
     */
    getContextData() {
        return this.context;
    }

    /**
     * Generates a formatted string summary of the context.
     * This string is intended for use in LLM prompts (e.g., for the Architect).
     *
     * @returns {string} - A formatted string containing the global summary and recent chapter events.
     */
    getContextSummary() {
        const recentText = this.context.recentChapters
            .map(c => `Chapter ${c.number}: ${c.summary}`)
            .join("\n");

        return `
Previous Story Summary: ${this.context.globalSummary}

Recent Events:
${recentText}
        `.trim();
    }

    /**
     * Updates the context with a new chapter's summary.
     * Adds the new chapter to the recent chapters list and triggers pruning if necessary.
     *
     * @param {number|string} chapterNum - The number of the completed chapter.
     * @param {string} chapterSummary - The summary of the completed chapter (generated by the Architect).
     */
    updateContext(chapterNum, chapterSummary) {
        this.context.currentChapter = parseInt(chapterNum);

        // Add to recent chapters
        this.context.recentChapters.push({
            number: chapterNum,
            summary: chapterSummary
        });

        // Sort by chapter number just in case
        this.context.recentChapters.sort((a, b) => a.number - b.number);

        // Pruning logic: If we have > 25 chapters in the buffer
        if (this.context.recentChapters.length > 25) {
            this.pruneContext();
        }
    }

    /**
     * Prunes the recent chapters buffer to maintain a manageable size.
     * Moves the oldest chapters from the buffer into the global summary.
     * Prevents the global summary from growing indefinitely by truncating it if needed.
     */
    pruneContext() {
        console.log("Pruning context...");
        const chaptersToArchive = this.context.recentChapters.slice(0, -25); // Get the ones overflowing
        this.context.recentChapters = this.context.recentChapters.slice(-25); // Keep last 25

        const archiveText = chaptersToArchive
            .map(c => `[Ch.${c.number}] ${c.summary}`)
            .join(" ");

        this.context.globalSummary += " " + archiveText;

        // Limit global summary length roughly if it gets too huge (simple truncation for safety)
        if (this.context.globalSummary.length > 5000) {
            this.context.globalSummary = "..." + this.context.globalSummary.slice(-5000);
        }
    }
}
